# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vaccination',
            new_name='Vaccine',
        ),
        migrations.RenameModel(
            old_name='VaccinationIntroduction',
            new_name='VaccineIntroduction',
        ),
        migrations.RenameField(
            model_name='vaccinationestimate',
            old_name='vaccination',
            new_name='vaccine',
        ),
        migrations.RenameField(
            model_name='vaccineintroduction',
            old_name='vaccination',
            new_name='vaccine',
        ),
    ]
