# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160307_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationestimate',
            name='estimate',
            field=models.IntegerField(),
        ),
    ]
