# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160307_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinationestimate',
            old_name='estimate',
            new_name='coverage',
        ),
    ]
