# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160307_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('short_name', models.CharField(max_length=20)),
                ('long_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='core.VaccineGroup'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='core.VaccineGroup'),
        ),
    ]
